### ISSUE TITLE
User can add selected ingredients for cooking 

### ISSUE THREAD

**Issue by Ost-Ethan** [Ost-Ethan/BOTW-Zelda-Cooking-ajax-project#1]
## ⚙️ Feature

User will be able to select from a list of ingredients to cook with.

## 📐 Functionality

The user will be able to select up to 5 ingredients at a time, from a list of ingredients by clicking on them. Ingredients will be highlighted when selected, and can be clicked again to unselect them. Selected ingredients will be stored in an array internally for use on the cooking page.

## 🖼️ Wireframes

> 
Desktop should look like this:
![image](https://github.com/Ost-Ethan/ajax-project/assets/136650513/2bc98399-50ef-4634-881a-ff2b3074f403)
Mobile should look like this:
![image](https://github.com/Ost-Ethan/ajax-project/assets/136650513/328202a9-abe4-4e5e-a895-ddfa62aa9350)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create an HTML skeleton for the page.
- [x] Add the page title header box at the top of the page.
- [x] Create and format the buttons for "Favorites", "Ingredient List" , and "Current Selection"
- [x] Create the columns for the ingredients, ensuring they scale down to one column for mobile devices.
- [x] Create a few "dummy" entries for ingredients that follow the format defined in the figma.
- [x] In JavaScript, Add an event listener to the ingredients container.
- [x] In the callback function of the event listener, check the `event.target` and set the CSS class to highlight the element of the clicked ingredient, and store the ingredient information in an array called `selectedIngredients`.  
- [x] In JavaScript, ensure that the length of the ingredient array does not exceed 5, and ensure that no more ingredients can be highlighted. 
- [x] Using the Hyrule Compendium API, and the format of the dummy ingredients, fill the information for all ingredients using the data called from the API.
- [x] Ensure all ingredients can be clicked on. 

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
