### ISSUE TITLE
User can remove selected ingredients

### ISSUE THREAD

**Issue by Ost-Ethan** [Ost-Ethan/BOTW-Zelda-Cooking-ajax-project#2]
## ⚙️ Feature

User can remove selected ingredients

## 📐 Functionality

User will be able to remove selected ingredients by selecting them again on the ingredients page, or by clicking the remove button on the "Cooking Selection" view.

## 🖼️ Wireframes

This is what mobile should look like:
![image](https://github.com/Ost-Ethan/ajax-project/assets/136650513/be96a30d-ff27-49cf-b9d2-0296b52f1bae)
This is what desktop should look like:
![image](https://github.com/Ost-Ethan/ajax-project/assets/136650513/796ba1cc-ceca-4188-89d1-4cfddb3ad3f3)

## ✅ Task List

- [x] Create a new view swap for the cooking selection view, and set the view from the previous page to "hidden" (a CSS class with `display: none`
- [x] Create the ingredient boxes as shown on the figma, with the X icons in the corner of the box. 
- [x] Create and format the bottom box for the resulting dish information
- [x] Using the `selectedIngredients` array, populate the ingredient boxes with the information associated with the ingredients at each index of the array.
- [x] In JavaScript, add an event listener to the X button on each ingredient, with an identifier that indicates what ingredient they are associated with. Example, in this case we would be adding the id of 1 to the anchor element to target the first ingredient in the array: `<a href="#" id = 1><fontawesome Icon></a>`
- [x] In the event listener callback function, use the `splice` method and remove the associated ingredient from the `selectedIngredients` array at the index of the id of the `event.target.getAttribute("id") - 1`.
- [x] Ensure that all remove buttons work, and that it resets the `textContent` of each ingredient box on the page when the element is removed. 
- [x] When no ingredient is present, replace the `textContent` with "No Selected ingredient."
- [x] In JavaScript, add an event listener to the header with a callback function for viewSwapping.
- [x] Create the `viewSwap` function to switch the views when the "ingredient list" button is clicked and when the "Cooking selection" button is clicked.
- [x] On your ingredient list view, add functionality for when a selected item is clicked, it removes the selected item from the `selectedIngredients` array and removes the highlight from the ingredient.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
