### ISSUE TITLE
User can view the cooked result of their ingredients

### ISSUE THREAD

**Issue by Ost-Ethan** [Ost-Ethan/BOTW-Zelda-Cooking-ajax-project#3]
## ⚙️ Feature

User can view the resulting heart information, food image, and additional status effect from the cooked dish, using the selected ingredients.

## 📐 Functionality

User will be able to see the resulting dish from the selected ingredients and information from that resulting dish, such as the status effects of the dish, or the hearts healed amount of the dish.

## 🖼️ Wireframes

Desktop should look like this:
![image](https://github.com/Ost-Ethan/ajax-project/assets/136650513/27e721b5-0660-448d-b1ed-3f0ea9ac2e18)
Mobile should look like this:
![image](https://github.com/Ost-Ethan/ajax-project/assets/136650513/ce156ff6-51a2-4e3b-9ff4-40c8ce1e369d)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a function to calculate and return the total amount of hearts restored. To calculate the amount of hearts healed from the dish, we need to multiply the `hearts_recovered` value of the ingredient by 2, and this can be stored in a `cookedHeartsRestored` variable. Then we need to add all of the `cookedHeartsRestored` values of the selected ingredients to show how many total hearts are restored from the dish.
- [x] Create a function that takes the `cooking_effect` values from each ingredient and returns a string that identifies the effect, if there is a valid effect, and tells what level the effect is. i.e `finishedCookingEffect(selectedIngredients){ const finalEffect = "Heat Ressistance Level 3" return finalEffect}` where `finalEffect` is calculated from the ingredients. This is simple, first we need to check if all the ingredients match the same effect. If they don't then the resulting dish won't have an effect. If they do have an effect, see how many ingredients have the effect. If it's 2 or less ingredients it is a level 1 effect, if it is 3 or 4 ingredients with the effect, it will be a level 2, and if it is all 5 it will be a level 5 effect. While this isn't how it works in the game, as each ingredient has it's own potency level in game, it will suffice for our calculator for now.
- [x] Take the resulting information from the functions, and display it as shown in the figma.
- [x] Create a function that assigns a food-type to each ingredient using the following id values:
 165- 173 is fruit
 174-185 are mushrooms
 186-199 are herbs/vegetables
- [x] Display the resulting picture of the dish based on the ingredients used. Images for the finished dishes can be found locally. We will limit the scope of this project to only a few images/ dish types, as dish type information is something we have to add for each ingredient ID. The limited dish types(7) are as follows:
For only `mushroom` type ingredients: Mushroom Skewer
For only fruit type items: Simmered Fruit
For only Herb/Vegetable type items: Fried Wild Greens
For mushroom and fruit: Fruit and Mushroom mix
For mushroom and herb/Vegetable: Steamed mushrooms
for fruit and Herb/Vegetable:  Steamed Fruit
If all 3 types are present, it will always be a "Steamed Mushrooms" dish.
-[ ] Ensure all information is being displayed correctly, with the correct picture.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
