### ISSUE TITLE
User can save favorite recipes

### ISSUE THREAD

**Issue by Ost-Ethan** [Ost-Ethan/BOTW-Zelda-Cooking-ajax-project#4]
## ⚙️ Feature

User can save recipes for later reference under the favorites tab

## 📐 Functionality

User will be able to click the favorite button, and it will save their current recipe under the favorites tab, and view all of their favorited recipes.

## 🖼️ Wireframes

Mobile should look like this: 
![image](https://github.com/Ost-Ethan/ajax-project/assets/136650513/178368c4-c440-4551-8fc5-52228489d32e)
Desktop should look like this:
![image](https://github.com/Ost-Ethan/ajax-project/assets/136650513/83d859c0-8a07-4188-91bf-bbf928734a23)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create and format the "Favorites" view
- [ ] Ensure the viewswap function works with the favorites view, 
- [ ] Add an event listener to the "Favorite" button on the "Cooking selection" view for `'click'` events.
- [ ] In the callback function for the event listener, write a function that stores the current values of the `selectedIngredients` array into a new data model for storing favorites called `favoriteRecipes`.
- [ ] Ensure `favoriteRecipies` has an empty array to store the selected ingredients.
- [ ] Create a renderFavorites function that runs when the favorites view is swapped that renders the stored information in `favoriteRecipies` and creates favorite entries as shown in the figma.
- [ ] Add  `onContentLoaded` and `beforeUnload` event listeners to the dom.
- [ ] in the `onContentLoaded` callback function, it should pull information from local storage for `favoriteRecipes` and render the stored entries
- [ ] in the `beforeUnload` callback function it should store the favorite entries in local storage.
- [ ] Make sure the content on the favorites page persists on page reload
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
