### ISSUE TITLE
User can remove favorite recipes

### ISSUE THREAD

**Issue by Ost-Ethan** [Ost-Ethan/BOTW-Zelda-Cooking-ajax-project#5]
## ⚙️ Feature

User can remove favorite recipes and view them in the cooking selection page.

## 📐 Functionality

User can click the delete button to remove recipes from the favorites list, as well as click the eye icon to view the recipes in the cooking selection view. A modal will pop up asking for confirmation before deleting.

## 🖼️ Wireframes
How the delete modal should look like:
![image](https://github.com/Ost-Ethan/ajax-project/assets/136650513/cac507d4-b756-4279-8a39-4a61f95c3f86)
Favorites view mobile:
![image](https://github.com/Ost-Ethan/ajax-project/assets/136650513/7fbd39d5-e9b4-48c7-895a-4019a4336d31)
Favorites view desktop: 
![image](https://github.com/Ost-Ethan/ajax-project/assets/136650513/99c1ba44-76eb-4576-9927-7f4fe85444a5)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create and format a modal that is a delete confirmation according to the figma. 
- [ ] Add an event listener to the font-awesome X icon on the favorites page.
- [ ] in the callback function, identify the entry in the `favoriteRecipes` array that the delete button corresponded to, and bring up the delete modal.
- [ ] Add functionality that when the confirm button is clicked on the modal, the entry is deleted, and if the cancel button is clicked it closes the modal. 
- [ ] Add an event listener to the font-awesome Eye icon.
- [ ] in the callback function, set the current selected ingredients to the values stored in the `favoriteRecipes` array at the index which corresponds to the entry clicked on. 
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
